#!/bin/bash

echo "🚀 PChat DHT使用指南"

echo "📋 启动多个客户端以建立DHT网络:"
echo "   1. 打开第一个终端，运行:"
echo "      ./bin/pchat -username Alice -port 9001"
echo ""
echo "   2. 等待几秒钟让Alice广播自己的信息到DHT网络"
echo ""
echo "   3. 打开第二个终端，运行:"
echo "      ./bin/pchat -username Bob -port 9002"
echo ""
echo "   4. 等待几秒钟让Bob广播自己的信息到DHT网络"
echo ""
echo "   5. 在Alice或Bob终端中，使用/call命令连接对方:"
echo "      /call Bob  (在Alice终端中)"
echo "      或"
echo "      /call Alice  (在Bob终端中)"
echo ""
echo "💡 DHT网络提示:"
echo "   - DHT网络需要至少2个节点才能正常工作"
echo "   - 用户信息需要一些时间来广播到DHT网络"
echo "   - 如果DHT查找失败，确保目标用户已启动并在同一网络中"
echo ""
echo "🔧 故障排除:"
echo "   - 如果仍然无法找到用户，可以尝试使用注册服务器模式"
echo "   - 确保防火墙没有阻止端口通信"
echo "   - 检查网络连接是否正常"